sequin:
  image:
    repository: sequin/sequin
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 7376
    nodePort: 31376
  config:
    pgHostname: sequin-postgres
    pgDatabase: sequin
    pgPort: 5432
    pgUsername: postgres
    pgPassword: postgres
    pgPoolSize: 20
    secretKeyBase: "wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If"
    vaultKey: "2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY="
    redisUrl: "redis://sequin-redis:6379"

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
    nodePort: 7377
  config:
    database: sequin
    username: postgres
    password: postgres
    walLevel: logical
  persistence:
    enabled: true
    size: 1Gi

redis:
  enabled: true
  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
    nodePort: 7378
  persistence:
    enabled: true
    size: 1Gi
