apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sequin
spec:
  type: {{ .Values.sequin.service.type }}
  ports:
    - port: {{ .Values.sequin.service.port }}
      targetPort: 7376
      nodePort: {{ .Values.sequin.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-sequin
---
{{ if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgres
{{- end }}
---
{{ if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
  selector:
    app: {{ .Release.Name }}-redis
{{- end }}
